from __future__ import annotations

import argparse
import os
import pickle
import time
from pathlib import Path
from typing import Any, Sequence

import numpy as np
from joblib import Parallel, delayed
from scipy.sparse import isspmatrix_csr

from SparseStochMat import inplace_csr_row_normalize
from compute_S_rate import conditional_entropy_of_T
from signal_generation import compute_inter_transition_matrices_for_lambda, ensure_laplacians


MOTIF_PATHS = {
    "merge_merge": Path("data/merge_merge.pkl"),
    "merge_split": Path("data/merge_split.pkl"),
    "split_merge": Path("data/split_merge.pkl"),
}

DEFAULT_LAMBDAS = np.logspace(-4, -1, 10)
DEFAULT_OUTPUT_BASE = Path("./gridsearch_results/motifs_global")
BACKEND = "loky"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Compute global entropy curves for the motif networks generated by "
            "generate_motifs.py, with optional backward-time curves."
        )
    )
    parser.add_argument(
        "--motifs",
        nargs="+",
        default=list(MOTIF_PATHS),
        choices=sorted(MOTIF_PATHS),
        help="Subset of motif datasets to process.",
    )
    parser.add_argument(
        "--lambdas",
        nargs="+",
        type=float,
        default=DEFAULT_LAMBDAS.tolist(),
        help="Lambda values to evaluate.",
    )
    parser.add_argument(
        "--output-base",
        type=Path,
        default=DEFAULT_OUTPUT_BASE,
        help="Base directory where outputs will be written.",
    )
    parser.add_argument(
        "--n-jobs",
        type=int,
        default=min(4, len(DEFAULT_LAMBDAS), os.cpu_count() or 1),
        help="Number of parallel workers across lambda blocks per motif.",
    )
    parser.add_argument(
        "--reverse-time",
        action="store_true",
        help="Compute backward entropy curves instead of forward ones.",
    )
    return parser.parse_args()


def load_motif_network(path: str | Path) -> Any:
    with open(path, "rb") as handle:
        return pickle.load(handle)


def lambda_blocks(lambdas: Sequence[float], n_jobs: int) -> list[list[float]]:
    effective_jobs = max(1, int(n_jobs))
    blocks = np.array_split(np.asarray(lambdas, dtype=float), effective_jobs)
    return [block.tolist() for block in blocks if len(block) > 0]


def direction_label(reverse_time: bool) -> str:
    return "backward" if reverse_time else "forward"


def signal_subdir(reverse_time: bool) -> str:
    return "global_S_rev" if reverse_time else "global_S"


def signal_filename(lamda: float) -> str:
    return f"global_S{float(lamda):.11f}"


def direction_metadata_filename(reverse_time: bool) -> str:
    return f"metadata_{direction_label(reverse_time)}.pkl"


def copy_matrix(matrix):
    if hasattr(matrix, "copy"):
        return matrix.copy()
    return np.array(matrix, copy=True)


def ensure_csr(matrix):
    if not isspmatrix_csr(matrix):
        return matrix.tocsr()
    return matrix


def global_time_samples(net: Any, num_steps: int) -> np.ndarray:
    return np.asarray(net.times[:num_steps], dtype=float)


def compute_global_entropy_curve(
    net: Any,
    lamda: float,
    reverse_time: bool = False,
) -> dict[str, Any]:
    compute_inter_transition_matrices_for_lambda(net, float(lamda))
    source_mats = net.inter_T[float(lamda)]
    num_steps = len(source_mats)
    t_samples = global_time_samples(net, num_steps=num_steps)
    k_samples = np.arange(num_steps, dtype=int)
    values = np.empty(num_steps, dtype=float)
    p0 = np.ones(net.num_nodes, dtype=float) / float(net.num_nodes)

    if num_steps == 0:
        values = np.array([], dtype=float)
    elif reverse_time:
        cumulative = ensure_csr(copy_matrix(source_mats[-1]))
        values[-1] = conditional_entropy_of_T(cumulative, p0)
        for idx in range(num_steps - 2, -1, -1):
            cumulative = ensure_csr(cumulative @ source_mats[idx])
            inplace_csr_row_normalize(cumulative)
            values[idx] = conditional_entropy_of_T(cumulative, p0)
    else:
        cumulative = ensure_csr(copy_matrix(source_mats[0]))
        values[0] = conditional_entropy_of_T(cumulative, p0)
        for idx in range(1, num_steps):
            cumulative = ensure_csr(cumulative @ source_mats[idx])
            inplace_csr_row_normalize(cumulative)
            values[idx] = conditional_entropy_of_T(cumulative, p0)

    return {
        "lamda": f"{float(lamda):.11f}",
        "lamda_float": float(lamda),
        "k_samples": k_samples,
        "t_samples": t_samples,
        "signal": values,
        "signal_array": values,
        "reverse_time": bool(reverse_time),
        "direction": direction_label(reverse_time),
        "curve_kind": "global_entropy",
        "statistic": "conditional entropy of cumulative transition matrices",
        "num_steps": int(num_steps),
    }


def clear_lambda_cache(net: Any, lamda: float) -> None:
    for attr in ("inter_T", "inter_T_lin", "T", "T_lin", "window_T", "S"):
        value = getattr(net, attr, None)
        if isinstance(value, dict) and float(lamda) in value:
            del value[float(lamda)]


def save_global_signal(signal_result: dict[str, Any], motif_output_dir: Path) -> None:
    lamda = float(signal_result["lamda_float"])
    outdir = motif_output_dir / signal_subdir(bool(signal_result.get("reverse_time", False)))
    outdir.mkdir(parents=True, exist_ok=True)
    with open(outdir / signal_filename(lamda), "wb") as handle:
        pickle.dump(signal_result, handle)


def save_metadata(
    motif_name: str,
    network_path: Path,
    net: Any,
    lambdas: Sequence[float],
    output_dir: Path,
    n_jobs: int,
    reverse_time: bool,
    elapsed_seconds: float | None = None,
) -> None:
    direction = direction_label(reverse_time)
    metadata = {
        "motif_name": motif_name,
        "network_path": str(network_path),
        "num_nodes": int(net.num_nodes),
        "num_events": int(net.num_events),
        "num_times": int(len(net.times)),
        "lambdas": np.asarray(lambdas, dtype=float),
        "n_jobs": int(n_jobs),
        "reverse_time": bool(reverse_time),
        "direction": direction,
        "signal_subdir": signal_subdir(reverse_time),
        "curve_kind": "global_entropy",
        "elapsed_seconds": elapsed_seconds,
    }
    output_dir.mkdir(parents=True, exist_ok=True)
    with open(output_dir / direction_metadata_filename(reverse_time), "wb") as handle:
        pickle.dump(metadata, handle)

    shared_path = output_dir / "metadata.pkl"
    shared_metadata = {}
    if shared_path.exists():
        with open(shared_path, "rb") as handle:
            shared_metadata = pickle.load(handle)

    shared_metadata.update(
        {
            "motif_name": motif_name,
            "network_path": str(network_path),
            "num_nodes": int(net.num_nodes),
            "num_events": int(net.num_events),
            "num_times": int(len(net.times)),
            "curve_kind": "global_entropy",
        }
    )
    shared_metadata[f"{direction}_lambdas"] = np.asarray(lambdas, dtype=float)
    shared_metadata[f"{direction}_n_jobs"] = int(n_jobs)
    shared_metadata[f"{direction}_elapsed_seconds"] = elapsed_seconds
    shared_metadata[f"{direction}_signal_subdir"] = signal_subdir(reverse_time)
    shared_metadata[f"{direction}_metadata_file"] = direction_metadata_filename(reverse_time)

    with open(shared_path, "wb") as handle:
        pickle.dump(shared_metadata, handle)


def worker(
    net: Any,
    lamda_block: Sequence[float],
    motif_output_dir: Path,
    reverse_time: bool,
) -> list[float]:
    finished = []
    for lamda in lamda_block:
        result = compute_global_entropy_curve(
            net=net,
            lamda=float(lamda),
            reverse_time=reverse_time,
        )
        save_global_signal(result, motif_output_dir=motif_output_dir)
        clear_lambda_cache(net, float(lamda))
        finished.append(float(lamda))

    print("finished lambda block:", [f"{lamda:.11f}" for lamda in finished])
    return finished


def compute_global_entropy_curves_for_motif(
    motif_name: str,
    network_path: Path,
    lambdas: Sequence[float],
    output_base: Path,
    n_jobs: int,
    reverse_time: bool = False,
) -> None:
    motif_output_dir = output_base / motif_name
    net = load_motif_network(network_path)
    ensure_laplacians(net)

    save_metadata(
        motif_name=motif_name,
        network_path=network_path,
        net=net,
        lambdas=lambdas,
        output_dir=motif_output_dir,
        n_jobs=n_jobs,
        reverse_time=reverse_time,
    )

    t_start = time.time()
    blocks = lambda_blocks(lambdas, n_jobs=n_jobs)

    if len(blocks) == 1:
        worker(
            net=net,
            lamda_block=blocks[0],
            motif_output_dir=motif_output_dir,
            reverse_time=reverse_time,
        )
    else:
        Parallel(n_jobs=len(blocks), backend=BACKEND)(
            delayed(worker)(
                net=net,
                lamda_block=block,
                motif_output_dir=motif_output_dir,
                reverse_time=reverse_time,
            )
            for block in blocks
        )

    elapsed = time.time() - t_start
    save_metadata(
        motif_name=motif_name,
        network_path=network_path,
        net=net,
        lambdas=lambdas,
        output_dir=motif_output_dir,
        n_jobs=n_jobs,
        reverse_time=reverse_time,
        elapsed_seconds=elapsed,
    )

    hours, rem = divmod(elapsed, 3600)
    minutes, seconds = divmod(rem, 60)
    print(
        f"{motif_name}: {elapsed:.2f} s "
        f"({int(hours):02d}:{int(minutes):02d}:{seconds:05.2f})"
    )


def main() -> None:
    args = parse_args()
    lambdas = [float(lamda) for lamda in args.lambdas]

    for motif_name in args.motifs:
        network_path = MOTIF_PATHS[motif_name]
        compute_global_entropy_curves_for_motif(
            motif_name=motif_name,
            network_path=network_path,
            lambdas=lambdas,
            output_base=args.output_base,
            n_jobs=int(args.n_jobs),
            reverse_time=bool(args.reverse_time),
        )


if __name__ == "__main__":
    main()
