from __future__ import annotations

import argparse
import os
import pickle
import time
from pathlib import Path
from typing import Any, Sequence

import numpy as np
from joblib import Parallel, delayed

from signal_generation import (
    PreparedSignalSample,
    WindowSamplingPlan,
    compute_signals_for_lambdas_prepared,
    prepare_signal_sample,
    save_signal_result,
)


MOTIF_PATHS = {
    "merge_merge": Path("data/merge_merge.pkl"),
    "merge_split": Path("data/merge_split.pkl"),
    "split_merge": Path("data/split_merge.pkl"),
}

DEFAULT_LAMBDAS = np.logspace(-4, -1, 10)
DEFAULT_WINDOWS = [1.0, 5.0, 10.0, 25.0]
DEFAULT_OUTPUT_BASE = Path("./gridsearch_results/motifs")
WINDOW_BACKEND = "segment_tree"
BACKEND = "loky"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Compute windowed entropy curves for the motif networks generated by "
            "generate_motifs.py using the shared signal_generation pipeline."
        )
    )
    parser.add_argument(
        "--motifs",
        nargs="+",
        default=list(MOTIF_PATHS),
        choices=sorted(MOTIF_PATHS),
        help="Subset of motif datasets to process.",
    )
    parser.add_argument(
        "--lambdas",
        nargs="+",
        type=float,
        default=DEFAULT_LAMBDAS.tolist(),
        help="Lambda values to evaluate.",
    )
    parser.add_argument(
        "--windows",
        nargs="+",
        type=float,
        default=DEFAULT_WINDOWS,
        help="Window lengths to evaluate.",
    )
    parser.add_argument(
        "--sample-fraction",
        type=float,
        default=1.0,
        help=(
            "Fraction of valid window starts to sample. Use 1.0 to compute full "
            "entropy curves."
        ),
    )
    parser.add_argument(
        "--output-base",
        type=Path,
        default=DEFAULT_OUTPUT_BASE,
        help="Base directory where outputs will be written.",
    )
    parser.add_argument(
        "--n-jobs",
        type=int,
        default=min(4, len(DEFAULT_LAMBDAS), os.cpu_count() or 1),
        help="Number of parallel workers across lambda blocks per motif.",
    )
    return parser.parse_args()


def normalize_windows(windows: Sequence[float]) -> tuple[float, ...]:
    return tuple(dict.fromkeys(float(window) for window in windows))


def load_motif_network(path: str | Path) -> Any:
    with open(path, "rb") as handle:
        return pickle.load(handle)


def prepare_full_window_sample(
    net: Any,
    windows: Sequence[float],
) -> PreparedSignalSample:
    windows_tuple = normalize_windows(windows)
    p0 = np.ones(net.num_nodes, dtype=float) / net.num_nodes

    net.compute_laplacian_matrices(
        t_start=net.times[0],
        t_stop=net.times[-1],
        random_walk=False,
    )

    window_plans: dict[float, WindowSamplingPlan] = {}
    for window in windows_tuple:
        considered_times = net.times[net.times < net.times[-1] - window]
        num_windows = len(considered_times)

        if num_windows <= 0:
            k_samples = np.array([], dtype=int)
            t_samples = np.array([], dtype=float)
            window_ends = np.array([], dtype=np.int64)
        else:
            k_samples = np.arange(num_windows, dtype=int)
            t_samples = np.asarray(net.times[k_samples], dtype=float)
            window_ends = np.asarray(
                net._get_window_ends_vectorized(window, n_windows=num_windows),
                dtype=np.int64,
            )

        window_plans[float(window)] = WindowSamplingPlan(
            window=float(window),
            k_samples=k_samples,
            t_samples=t_samples,
            window_ends=window_ends,
        )

    return PreparedSignalSample(
        net=net,
        windows=windows_tuple,
        sample_fraction=1.0,
        p0=p0,
        window_plans=window_plans,
    )


def prepare_motif_sample(
    net: Any,
    windows: Sequence[float],
    sample_fraction: float,
) -> PreparedSignalSample:
    if sample_fraction >= 1.0:
        return prepare_full_window_sample(net=net, windows=windows)

    return prepare_signal_sample(
        net=net,
        windows=windows,
        sample_fraction=sample_fraction,
        p0=np.ones(net.num_nodes, dtype=float) / net.num_nodes,
    )


def lambda_blocks(lambdas: Sequence[float], n_jobs: int) -> list[list[float]]:
    effective_jobs = max(1, int(n_jobs))
    blocks = np.array_split(np.asarray(lambdas, dtype=float), effective_jobs)
    return [block.tolist() for block in blocks if len(block) > 0]


def save_window_signal_legacy(
    signal_result: dict[str, Any],
    output_base: Path,
) -> None:
    lamda = float(signal_result["lamda"])
    window = float(signal_result["window"])
    lamda_key = f"{lamda:.11f}"
    window_key = f"{window:g}"
    signal_array = np.asarray(signal_result["signal"], dtype=float)

    payload = {
        "lamda": lamda_key,
        "lamda_float": lamda,
        "window": window,
        "k_samples": np.asarray(signal_result["k_samples"], dtype=int),
        "t_samples": np.asarray(signal_result["t_samples"], dtype=float),
        "signal": signal_array,
        "signal_array": signal_array,
    }

    outdir = output_base / "window_S" / window_key
    outdir.mkdir(parents=True, exist_ok=True)
    with open(outdir / f"window_S{lamda_key}", "wb") as handle:
        pickle.dump(payload, handle)


def save_lambda_block_results(
    signals_by_lambda: dict[float, dict[float, dict[str, Any]]],
    motif_output_dir: Path,
) -> None:
    signal_dir = motif_output_dir / "signals"
    for window_results in signals_by_lambda.values():
        for signal_result in window_results.values():
            save_signal_result(signal_result, signal_dir)
            save_window_signal_legacy(signal_result, motif_output_dir)


def save_metadata(
    motif_name: str,
    network_path: Path,
    prepared: PreparedSignalSample,
    lambdas: Sequence[float],
    output_dir: Path,
    sample_fraction: float,
    n_jobs: int,
    elapsed_seconds: float | None = None,
) -> None:
    metadata = {
        "motif_name": motif_name,
        "network_path": str(network_path),
        "num_nodes": int(prepared.net.num_nodes),
        "num_events": int(prepared.net.num_events),
        "num_times": int(len(prepared.net.times)),
        "lambdas": np.asarray(lambdas, dtype=float),
        "windows": np.asarray(prepared.windows, dtype=float),
        "sample_fraction": float(sample_fraction),
        "n_jobs": int(n_jobs),
        "window_backend": WINDOW_BACKEND,
        "elapsed_seconds": elapsed_seconds,
    }
    output_dir.mkdir(parents=True, exist_ok=True)
    with open(output_dir / "metadata.pkl", "wb") as handle:
        pickle.dump(metadata, handle)


def worker(
    prepared: PreparedSignalSample,
    lamda_block: Sequence[float],
    motif_output_dir: Path,
) -> list[float]:
    signals_by_lambda = compute_signals_for_lambdas_prepared(
        prepared=prepared,
        lambdas=lamda_block,
        use_linear_approx=False,
        lin_t_s=10,
        window_backend=WINDOW_BACKEND,
    )
    save_lambda_block_results(
        signals_by_lambda=signals_by_lambda,
        motif_output_dir=motif_output_dir,
    )
    finished = [float(lamda) for lamda in lamda_block]
    print("finished lambda block:", [f"{lamda:.11f}" for lamda in finished])
    return finished


def compute_entropy_curves_for_motif(
    motif_name: str,
    network_path: Path,
    lambdas: Sequence[float],
    windows: Sequence[float],
    sample_fraction: float,
    output_base: Path,
    n_jobs: int,
) -> None:
    motif_output_dir = output_base / motif_name
    net = load_motif_network(network_path)
    prepared = prepare_motif_sample(
        net=net,
        windows=windows,
        sample_fraction=sample_fraction,
    )

    save_metadata(
        motif_name=motif_name,
        network_path=network_path,
        prepared=prepared,
        lambdas=lambdas,
        output_dir=motif_output_dir,
        sample_fraction=sample_fraction,
        n_jobs=n_jobs,
    )

    t_start = time.time()
    blocks = lambda_blocks(lambdas, n_jobs=n_jobs)

    if len(blocks) == 1:
        worker(prepared=prepared, lamda_block=blocks[0], motif_output_dir=motif_output_dir)
    else:
        Parallel(n_jobs=len(blocks), backend=BACKEND)(
            delayed(worker)(
                prepared=prepared,
                lamda_block=block,
                motif_output_dir=motif_output_dir,
            )
            for block in blocks
        )

    elapsed = time.time() - t_start
    save_metadata(
        motif_name=motif_name,
        network_path=network_path,
        prepared=prepared,
        lambdas=lambdas,
        output_dir=motif_output_dir,
        sample_fraction=sample_fraction,
        n_jobs=n_jobs,
        elapsed_seconds=elapsed,
    )

    hours, rem = divmod(elapsed, 3600)
    minutes, seconds = divmod(rem, 60)
    print(
        f"{motif_name}: {elapsed:.2f} s "
        f"({int(hours):02d}:{int(minutes):02d}:{seconds:05.2f})"
    )


def main() -> None:
    args = parse_args()
    lambdas = [float(lamda) for lamda in args.lambdas]
    windows = [float(window) for window in args.windows]

    for motif_name in args.motifs:
        network_path = MOTIF_PATHS[motif_name]
        compute_entropy_curves_for_motif(
            motif_name=motif_name,
            network_path=network_path,
            lambdas=lambdas,
            windows=windows,
            sample_fraction=float(args.sample_fraction),
            output_base=args.output_base,
            n_jobs=int(args.n_jobs),
        )


if __name__ == "__main__":
    main()
